---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp grammy_nominations.json $DEPLOYPATH
    - /bin/cp -R album-rating $DEPLOYPATH
    - /bin/cp -R grammies-pick-em $DEPLOYPATH
    - /bin/cp -R song-battle $DEPLOYPATH
    - /bin/cp -R song-search $DEPLOYPATH
